name: docker-build

on:
  push:
  pull_request:

jobs:
  multi-arch-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: erisamoe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Bake image
        uses: docker/bake-action@v6
        env:
          MULTI_PLATFORM: true
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max